### PR TITLE
Add `from_i128_with_scale_rslt` 

### PR DESCRIPTION
**Pull request by c410-f3r**
@paupino Feel free to close this PR if the changes aren't desirable.

My use-case: External stream of bytes that represent `i128` decimals are received but can't be trusted so a check is necessary to ensure correctness and recovery. With `from_i128_with_scale`, the binary will simply halt execution as there is currently no way to verify if `i128` or `u32` are valid, thus the creation of `from_i128_with_scale_rslt`.

### CODE REVIEW

**Comment by paupino** [comment]
This PR is great - it's also starting to clean up the error handling which is long overdue. The one hangup I have is on the naming of the function. In [version 2](#354) I'll do a holistic clean up of the API, but for now I'm just wondering if there is a better name? Admittedly I had to look up what `rslt` stood for - which seems obvious now on retrospect! 
I don't have a better name just yet - perhaps this one is ok? Anyway, let me mull on it for a bit.

**Comment by c410-f3r** [comment]
@paupino Thanks! Some say that naming is one of the most difficult things in the programming field :)
What the standard library do is prefixing with `try_` (`try_from` or `try_reserve`), so `from_i128_with_scale_rslt` would become `try_from_i128_with_scale`. There are also `checked_` variants like `checked_add` or `checked_mul`. In any case, feel free to pick the most appropriated name.

**Comment by paupino** [comment]
I liked the `try_` approach so renamed it to that before merge - thanks for your help!

**Comment by c410-f3r** [comment]
Thank you ! :D

**Pull request merged**
