### PR TITLE
Makes `const_fn` a default feature

### PR DESCRIPTION
**Pull request by devashishdxt**
Details:

- Removes `const_fn` and `lazy_static` features from feature list.
- Defaults all branches of conditional compilation with `const_fn` route.
- Removes `lazy_static` dependency.

Fixes https://github.com/paupino/rust-decimal/issues/186.

### CODE REVIEW

**Comment by devashishdxt** [comment]
@paupino: Can you please review this?

**Comment by paupino** [comment]
The changes look good. I wonder however if the feature flag should instead be reversed - that is, enabled by default but still available (similar to `no_std`) so that older versions of the Rust compilers can still use this? That way, by default we can keep adding new compiler features to the library but at the same time still support older versions of Rust.

Let me think about that for a little, but also curious to hear your thoughts.

**Comment by devashishdxt** [comment]
I think instead of using features, we can use [select-rustc](https://crates.io/crates/select-rustc) to define default behaviour for different Rust versions.

**Comment by paupino** [comment]
Will likely just provide a minimum Rust Compiler version for now (i.e. https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1310-2018-12-06). For proper backwards compatible support I'd also need to address the build pipeline which may be something I can introduce in the future.

**Pull request merged**
