### PR TITLE
Version 1.12 with some internal housekeeping

### PR DESCRIPTION
**Pull request by paupino**

### CODE REVIEW

**Comment by abreis** [comment]
@paupino The removal of `Zero` from the prelude is a semver breaking change 🙂 this broke our pipelines.

**Comment by paupino** [comment]
Ugh, sorry - I'll add that back to `prelude`.

**Comment by paupino** [comment]
Hopefully that should now be fixed now @abreis. I yanked `1.12.0` and added `1.12.1` which adds `Zero` back to prelude.

**Comment by abreis** [comment]
Thanks so much for the quick response!

**Pull request merged**
